# Generated by Django 4.0.4 on 2022-04-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_cambio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodecambio',
            name='fecha',
            field=models.DateField(error_messages={'unique': 'Fecha duplicada.'}, unique=True),
        ),
    ]
