# Generated by Django 4.0.4 on 2022-04-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_cambio', '0002_alter_tipodecambio_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodecambio',
            name='cambio',
        ),
        migrations.AddField(
            model_name='tipodecambio',
            name='compra',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tipodecambio',
            name='venta',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
